config/routes.rb
ToastyTights::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :products
  resources :carts
  resources :order_items

  root to: 'static_pages#home'

  match '/about', to: 'static_pages#about'
  match '/faq', to: 'static_pages#faq'
  match '/shop', to: 'order_items#new'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :order_items, dependent: :destroy

  def add_product(product_id)
  	order_items.find_by_product_id(product_id)
  	order_items.build(product_id: product_id)
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  attr_accessible :cart_id, :product_id, :quantity

  validates :quantity, numericality: { greater_than: 0, less_than_or_equal_to: 10 }
  
  def enough_in_stock(order_item_quantity)
    if order_item.quantity > product.in_stock
      self.errors.add(:quantity, "Please try again with a smaller quantity")
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :color, :in_stock, :price, :size
  has_many :order_items
  				  # :enough_in_stock

  validates :color, inclusion: { :in => %w(Black Charcoal Wine Plum) }
  validates :in_stock, numericality: { greater_than_or_equal_to: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :size, inclusion: { :in => %w(S M L Children's) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery 

  private 

    def current_cart
      Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      cart = Cart.create
      session[:cart_id] = cart.id
      cart
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def new
    @cart = Cart.new
  end

  def destroy
  	@cart = current_cart
  	@cart.destroy
  	session[:cart_id] = nil
  	redirect_to shop_path, notice: 'Your shopping cart is now empty.'
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def new
  	@order_item = OrderItem.new
  end

  def index 
  	@products = Product.order(:id)
  end

  def create
    @cart = current_cart
  	@order_item = OrderItem.new(params[:order_item])

  	respond_to do |format|
  	  if @order_item.save
  	  	format.html { redirect_to 'order_items#shop', 
  	  		notice: 'Item was successfully added to cart' }
  	  	format.json { render json: @order_item,
  	  		status: :created, location: @order_item }
        # product.in_stock.count = product.in_stock.count - product.quantity
  	  else
  	    format.html { render action: "new" }
  	    format.json { render json: @order_item.errors,
  	      status: :unprocessable_entity }
  	  end
  	end
  end 

  def destroy
    @order_item = OrderItem.find(params[:id])
    @order_item.destroy
    redirect_to 'store#show', notice:  'Item was successfully 
                                      removed from your cart'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    product = Product.new
    head :ok
  end

  def create
    product = Product.create(params[:product])
    
    if product.save
      head :ok
    else
      render json: product.errors
    end
  end

  def destroy
  	product = Product.find(params[:id])
  	product.destroy
  	head :ok
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom">
  <p class="pull-right">Warm and Toasty Tights® of Pardue Ventures, LLC</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
  	<%= link_to "Warm & Toasty Tights", root_path, id: "logo" %>
    <nav>
	  <ul class="nav pull-right">
	    <li><%= link_to "Home", root_path %></li>
	    <li><%= link_to "Shop", shop_path %></li>
	    <li><%= link_to "FAQ", faq_path %></li>
	    <li><%= link_to "About", about_path %></li>
	  </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href='http://fonts.googleapis.com/css?family=Almendra+Display|Sacramento' 
                                                  rel='stylesheet' type='text/css'>
    <title>Warm and Toasty Tights</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	<div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/order_items/_form.html.erb
<%= form_for @order_item do |f| %>
  <div class="field">
  	<%= f.select(:product_id, options_for_select(Product.all.collect {|p| ["#{p.color} - #{p.size}", p.id ] })) %>
  </div>
  <div class="field">
  	<%= f.label :quantity %>
  	<%= f.number_field :quantity %>
  </div>
  <div class="actions">
  	<%= f.submit "Add to Cart" %>
  </div>
<% end %>

app/views/order_items/new.html.erb
<div class="row">
  <div class="span2">
  	<p> </p>
  </div>
  <div class="span8">
  	<div id="directions">
      <h3>Please select size, color, and quantity:</h3>
    </div>
    <div>
      <%= render 'form' %>
    </div>
  </div>
  <div class="span2">
  	<p> </p>
  </div>
</div>

app/views/products/shop.html.erb
<div class="row">
  <div class="span2">
  	<p> </p>
  </div>
  <div class="span8">
  	<div id="directions">
      <h3>Please select size, color, and quantity:</h3>
    </div>
    <div>
      <%= render 'form' %>
    </div>
  </div>
  <div class="span2">
  	<p> </p>
  </div>
</div>

app/views/static_pages/about.html.erb
<div class="row">
  <div class="span2">
  	<p> </p>
  </div>
  <div class="span8">
    <h3>About Us</h3>
      <div id="bio">
        <p>Our company was founded in 2010 with one mission: to supply you with the warmest tights on the market. Who wants to be stuck wearing pants all winter? Not us! Now, you don't have to either... wear Warm and Toasty Tights!</p>

        <p>Our plush, fleece-lined tights have a seamless appearance: they look just like regular tights! They would fit in at the office! But, the cozy fleece-lined interior keeps you warm on the chilliest winter day.</p>

        <p>Available in Black, Charcoal, Wine, and Plum</p>
      </div>
  </div>
  <div class="span2">
  	<p> </p>
  </div>
</div>

app/views/static_pages/faq.html.erb
<div class="row">
  <div class="span2">
  	<p> </p>
  </div>
  <div class="span8">
    <h3>Frequently Asked Questions</h3></br>
      <strong>How are WARM AND TOASTY TIGHTS different than regular tights? Are they really that warm?</strong>
	  <p>Our tights are made to withstand winter.  They are woven like regular tights, but have a fully-lined fleece interior. Within two steps of your front door (when the wind whips around your legs, but doesn't chill you to the core), you'll feel the difference. Also, WARM AND TOASTY TIGHTS don't tear or run. It also takes a lot longer for them to pill (that is, gather little fuzzies on them) than it does for a pair of regular thick tights. So, our tights last longer!</p>

	  <strong>But, do they really look like tights? Aren't they thick? Bunchy? Or downright funny? Can I wear them to work?</strong>
	  <p>They really look like a regular pair of opaque tights!  You get the warmth of leggings with the more formal look of tights.  You can wear them with your favorite pencil skirt, that jazzy cocktail dress, or casual cotton to the office, a party, or on a winter walk through the park.   No one will notice a difference!  As for the fit, they are form-fitting and won't look bunchy.  The foot is no thicker than a pair of standard dress socks; so, you can wear them with boots, pumps, flats, or stilettos!</p>

	  <strong>What are WARM AND TOASTY TIGHTS made of?</strong>
	  <p>95% Bamboo Fiber; 5% Spandex</p>

	  <strong>What size should I order?</strong>
	  <p>Please see our size chart.</p>

	  <strong>What are the proper care instructions for WARM AND TOASTY TIGHTS?</strong>
	  <p>Handwash in cold water with like colors. Line dry to remove wrinkles. Color bleeding normal with first wash. 
	  Wash before wearing to prevent the transfer of color to other fabrics.</p>

	  <strong>Do you ship internationally?</strong>
	  <p>At the moment, no. We currently ship domestically within the United States.</p>

	  <strong>What is your return policy?</strong>
	  <p>We offer full refunds. Please email orders@warmandtoastytights.com for details.</p>
  </div>
  <div class="span2">
    <p> </p>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="span2">
  	<p> </p>
  </div>
  <div class="span8">
    <h3>Our Mission:</h3>
     <p>To supply you with the warmest tights on the market.</p>
  </div>
  <div class="span2">
  	<p> </p>
  </div>
</div>